title = "New Blog"
description = "The new Terrillo Blog is here! In a world AI generated content, I'm still writing our own articles."
topic = "Internal"
published = "October 3, 2024"

markdown = """

Born in New Orleans, LA. Terrillo is an Award-Winning Technology Leader. Directed technology teams as a consultant and worked for Marketing Agency, Technology, and Media company from 2012 to 2022. Founded Khabin Technology in 2020. Software Technology Consulting and Development.

"""
